name: Format code

on:
  push:
    branches:
      - '*'
      - '!main'

permissions: write-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ":robot: Format code with black"
        run: |
          pip install black
          black .
      - name: Test ${{ github.event.push.head }} docstring coverage
        run: |
          pip install docstr-coverage
          docstr-coverage src/sysml2py --badge=doc-cov --fail-under=0 -e ".*/(textx|tests)"
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: ":robot: Format code with black"
          add: "."
          branch: ${{ github.ref }}
