name: Deploy Sphinx documentation to Pages

on: [push]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
    - name: Get code coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls pytest
        coverage run --source=src -m pytest tests/
        coveralls
    - name: Get ${{ github.event.pull_request.base.sha }} coverage
      run: |
        pip install docstr-coverage
        git checkout $BASE
        echo "BASE_COV=$(docstr-coverage -p)" >> $GITHUB_ENV

    - name: Test ${{ github.event.pull_request.head.sha }} coverage
      run: |
        echo "$BASE coverage was: $BASE_COV%"
        git checkout $HEAD
        docstr-coverage --fail-under=$BASE_COV
