name: Deploy Sphinx documentation to Pages

on: [push]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
    - name: Get code coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls pytest
        coverage run --source=mypkg -m pytest tests/
        coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1
