name: Deploy Sphinx documentation to Pages

on: [push]

jobs:
  pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source
    - name: Get code coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls pytest
        python3.9 -m coverage run --source=src -m pytest tests/ && coverage report
        coveralls
    - name: Test ${{ github.event.push.head }} coverage
      run: |
        pip install docstr-coverage
        docstr-coverage src/sysml2py --badge=doc-cov
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ github.actor }}@users.noreply.github.com
        message: ":robot: Add coverage badge"
        add: "doc-cov.svg"
        branch: ${{ github.ref }}
