on:
  push:
    branches:
    - main

permissions: write-all

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    concurrency: push

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_API_TOKEN }}
