name: Test Commit

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test ${{ github.event.push.head }} coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install coveralls pytest pyyaml textx
          python -m coverage run --source=src -m pytest /tests && coverage report
          coveralls
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov pytest-timeout pytest-html
          pytest --timeout=300 . --doctest-modules --html=report-${{ matrix.python-version }}.html --self-contained-html --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=com --cov-report=xml --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-junit-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-results-${{ matrix.python-version }}
          path: report-${{ matrix.python-version }}.html
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
